apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
        - name: backstage
          image: allardkrings/backstage:1.42.3b
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "7007"
            - name: POSTGRES_USER
              value: backstage
            - name: POSTGRES_PASSWORD
              value: backstage
            - name: POSTGRES_DB
              value: backstage
            - name: POSTGRES_SERVICE_HOST
              value: postgres13.postgres.svc.cluster.local
            - name: POSTGRES_SERVICE_PORT
              value: "5432"
            - name: APP_CONFIG_auth_environment
              value: development
            - name: NODE_ENV
              value: development
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-token
                  key: GITHUB_TOKEN
            - name: GITEA_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gitea-token
                  key: GITEA_TOKEN
          volumeMounts:
            # Mount the configmap as a single file
            - mountPath: /app/app-config.production.yaml
              subPath: app-config.yaml
              name: app-configmap
            # Mount the PVC as the TechDocs storage directory
            - mountPath: /tmp/techdocs-storage
              name: techdocs-storage
      volumes:
        # ConfigMap for app config
        - name: app-configmap
          configMap:
            name: backstage-app-config
        # PVC for TechDocs storage
        - name: techdocs-storage
          persistentVolumeClaim:
            claimName: backstage-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: backstage
  namespace: backstage
spec:
  type: ClusterIP
  selector:
    app: backstage
  ports:
    - name: http
      port: 7007
      targetPort: 7007

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: backstage-tls
  namespace: backstage
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`backstage-dev.allarddcs.nl`)
      kind: Rule
      services:
        - name: backstage
          port: 7007
  tls:
    secretName: backstage-dev.allarddcs.nl-tls
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: backstage-pv
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: 192.168.2.110
    path: /mnt/nfs_share/backstage/dev
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backstage-pvc
  namespace: backstage
spec:
  storageClassName: ""
  volumeName: backstage-pv
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi


