apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: roudcube-lp.allarddcs.nl-tls
  namespace: mail
spec:
  dnsNames:
  - roundcube-lp.allarddcs.nl
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt
  secretName: roundcube-lp.allarddcs.nl-tls
  usages:
  - digital signature
  - key encipherment
