apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres13
  namespace: postgres
spec:
  serviceName: postgres13
  replicas: 1
  selector:
    matchLabels:
      app: postgres13
  template:
    metadata:
      labels:
        app: postgres13
    spec:
      containers:
      - name: postgres13
        image: postgres:13
#        command: ["sh"]
#        args: ["-c", "while true; do echo $(date -u) >> /tmp/run.log; sleep 5; done"]
        ports:
          - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: harbor
        - name: POSTGRES_USER
          value: harbor
        - name: POSTGRES_PASSWORD
          value: harbor
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres
      volumes:
      - name: postgres
        persistentVolumeClaim:
          claimName: postgres13-pvc
      nodeSelector:
        kubernetes.io/arch: arm64
---
apiVersion: v1
kind: Service
metadata:
  name: postgres13
  namespace: postgres
  labels:
    name: postgres13
spec:
  type: ClusterIP
  ports:
    - port: 5432
      name: postgres
  selector:
    app: postgres13
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres13-pv
spec:
  storageClassName: ""
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: 192.168.2.110
    path: /mnt/nfs_share/postgres13dev
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres13-pvc
  namespace: postgres
spec:
  storageClassName: ""
  volumeName: postgres13-pv
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
