apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: git-clone-
  namespace: argo
spec:
  entrypoint: git-clone
  templates:
  - name: git-clone
    inputs:
      artifacts:
      - name: argo-source
        path: /src
        git:
          repo: gitea.gitea.svc.cluster.local/allard/olproperties.git
          usernameSecret:
            name: github-creds
            key: username
          passwordSecret:
            name: github-creds
            key: password
    container:
      image: allardkrings/riscv64-maven
      command: ["sh", "-c"]
      args: ["git status && ls && cat VERSION"]
      workingDir: /src
