apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: mongodb
spec:
 ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mongo
  namespace: mongodb
subsets:
  - addresses:
    - ip: 192.168.2.109
    ports:
    - port: 30513

