apiVersion: v1
kind: PersistentVolume
metadata:
  name: argo-workflows-pv
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.2.110
    path: /mnt/nfs_share/argo-workflows/riscv
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: argo-workflows-pvc
  namespace: argo
spec:
  storageClassName: ""
  volumeName: argo-workflows-pv
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
