apiVersion: v1
kind: Secret
metadata:
  name: harbor-credentials
data:
  config.json: ewoJImF1dGhzIjogewoJCSJjb3JlLmhhcmJvci5hbGxkY3MubmwiOiB7CgkJCSJhdXRoIjogIllXUnRhVzQ2U0dGeVltOXlNREZBIgoJCX0sCgkJImNvcmUuaGFyYm9yLmRvbWFpbiI6IHsKCQkJImF1dGgiOiAiWVdSdGFXNDZTR0Z5WW05eU1ERkEiCgkJfSwKCQkiaGFyYm9yLmFsbGRjcy5ubCI6IHsKCQkJImF1dGgiOiAiWVdSdGFXNDZTR0Z5WW05eU1ERkEiCgkJfSwKCQkiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvIjogewoJCQkiYXV0aCI6ICJZV3hzWVhKa2EzSnBibWR6T2t0MVltVnlibVYwWlhNd01VQT0iCgkJfQoJfQp9
