apiVersion: v1
kind: PersistentVolume
metadata:
  name: kaniko-workspace-pv
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: 192.168.40.100
    path: /mnt/nfs_share/tekton-kaniko
    readOnly: false

