apiVersion: apps/v1
kind: Deployment
metadata:
  name: fedoratest
  labels:
    app: fedoratest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fedora
  template:
    metadata:
      labels:
        app: fedora
    spec:
      containers:
      - name: fedora
        image: fedora
        command: ["/bin/bash", "-c", "--"]
        args: ["while true; do sleep 30; done;"]
        volumeMounts:
          - name: nfs-vol
            mountPath: /opt/nfs
      volumes:
        - name: nfs-vol
          nfs:
            server: 192.168.40.100
            path: /mnt/nfs_share
